---
apiVersion: v1
kind: Namespace
metadata:
  name: miztiik-automation-ns
  labels:
    name: miztiik-automation-ns
    dept: engineering
    team: red-shirts
    project: eks-security-with-network-policies
